import { ProductWithVendor } from '@/types/product';
import { VendorPricing } from '@/types/vendor';
import { mockVendors } from './vendors';

// Helper function to generate vendor pricing for a product
const generateVendorPricing = (
  basePrice: number,
  vendorIds: string[],
  hasDiscount: boolean = false
): VendorPricing[] => {
  return vendorIds.map((vendorId, index) => {
    const vendor = mockVendors.find((v) => v.id === vendorId)!;
    const priceVariation = basePrice * (0.9 + Math.random() * 0.2); // ±10% variation
    const price = Math.round(priceVariation * 100) / 100;
    const discount = hasDiscount ? Math.floor(Math.random() * 20) + 10 : 0;
    const originalPrice = discount > 0 ? Math.round((price / (1 - discount / 100)) * 100) / 100 : undefined;

    return {
      vendorId: vendor.id,
      vendorName: vendor.name,
      vendorRating: vendor.rating.overall,
      vendorLogo: vendor.logo,
      price,
      originalPrice,
      discount,
      inStock: Math.random() > 0.1, // 90% in stock
      stockQuantity: Math.floor(Math.random() * 200) + 50,
      deliveryTime: vendor.deliveryTime,
      distance: vendor.location.distanceFromUser || 0,
      isVerified: vendor.isVerified,
    };
  });
};

export const mockProductsEnhanced: ProductWithVendor[] = [
  {
    id: '1',
    name: 'Aspirin 325mg',
    genericName: 'Acetylsalicylic Acid',
    description: 'Pain reliever and fever reducer. Also used for heart attack prevention when taken daily as prescribed by doctor.',
    category: 'Pain Relief',
    subcategory: 'Analgesics',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop',
      'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400&h=400&fit=crop',
    ],
    prescriptionRequired: false,
    dosage: '325mg',
    strength: '325mg',
    form: 'Tablet',
    manufacturer: 'Bayer Healthcare',
    activeIngredients: ['Acetylsalicylic Acid 325mg'],
    uses: ['Pain relief', 'Fever reduction', 'Inflammation', 'Heart attack prevention'],
    sideEffects: ['Stomach upset', 'Heartburn', 'Drowsiness', 'Mild headache'],
    warnings: ['Do not use if allergic to aspirin', 'Consult doctor if you have stomach ulcers', 'Not for children with flu symptoms'],
    storageInstructions: 'Store at room temperature away from moisture and heat',
    isGenericAvailable: true,
    requiresRefrigeration: false,
    isControlledSubstance: false,
    vendorPricing: generateVendorPricing(12.99, ['vendor-1', 'vendor-2', 'vendor-3', 'vendor-5']),
    averageRating: 4.5,
    totalReviews: 234,
    isFeatured: true,
    isLatest: true,
    isDiscounted: false,
    lowestPrice: 11.49,
    highestPrice: 14.29,
    vendorCount: 4,
    createdAt: new Date('2024-12-15'),
    updatedAt: new Date('2025-01-20'),
  },
  {
    id: '2',
    name: 'Lisinopril 10mg',
    genericName: 'Lisinopril',
    description: 'ACE inhibitor used to treat high blood pressure and heart failure. Helps prevent strokes, heart attacks, and kidney problems.',
    category: 'Heart Health',
    subcategory: 'Blood Pressure',
    image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400&h=400&fit=crop',
    prescriptionRequired: true,
    dosage: '10mg',
    strength: '10mg',
    form: 'Tablet',
    manufacturer: 'Pfizer',
    activeIngredients: ['Lisinopril 10mg'],
    uses: ['High blood pressure', 'Heart failure', 'Post-heart attack treatment'],
    sideEffects: ['Dizziness', 'Headache', 'Persistent cough', 'Fatigue'],
    warnings: ['Do not use if pregnant', 'May cause dizziness', 'Avoid potassium supplements'],
    storageInstructions: 'Store at room temperature, protect from moisture',
    isGenericAvailable: true,
    genericSavings: 40,
    requiresRefrigeration: false,
    isControlledSubstance: false,
    vendorPricing: generateVendorPricing(24.99, ['vendor-1', 'vendor-2', 'vendor-4', 'vendor-6']),
    averageRating: 4.7,
    totalReviews: 456,
    isFeatured: true,
    isLatest: false,
    isDiscounted: true,
    lowestPrice: 22.49,
    highestPrice: 27.99,
    vendorCount: 4,
    createdAt: new Date('2024-10-05'),
    updatedAt: new Date('2025-01-18'),
  },
  {
    id: '3',
    name: 'Metformin 500mg',
    genericName: 'Metformin HCl',
    description: 'First-line medication for type 2 diabetes. Helps control blood sugar levels and improve insulin sensitivity.',
    category: 'Diabetes',
    subcategory: 'Blood Sugar Control',
    image: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&h=400&fit=crop',
    prescriptionRequired: true,
    dosage: '500mg',
    strength: '500mg',
    form: 'Tablet',
    manufacturer: 'Bristol-Myers Squibb',
    activeIngredients: ['Metformin Hydrochloride 500mg'],
    uses: ['Type 2 diabetes', 'Insulin resistance', 'PCOS management'],
    sideEffects: ['Nausea', 'Diarrhea', 'Stomach upset', 'Metallic taste'],
    warnings: ['Take with food', 'Avoid alcohol', 'Monitor kidney function regularly'],
    storageInstructions: 'Store at room temperature, keep in original container',
    isGenericAvailable: true,
    genericSavings: 35,
    requiresRefrigeration: false,
    isControlledSubstance: false,
    vendorPricing: generateVendorPricing(19.99, ['vendor-1', 'vendor-3', 'vendor-4', 'vendor-5', 'vendor-6']),
    averageRating: 4.6,
    totalReviews: 589,
    isFeatured: true,
    isLatest: false,
    isDiscounted: true,
    lowestPrice: 17.99,
    highestPrice: 21.99,
    vendorCount: 5,
    createdAt: new Date('2024-09-20'),
    updatedAt: new Date('2025-01-15'),
  },
  {
    id: '4',
    name: 'Atorvastatin 20mg',
    genericName: 'Atorvastatin Calcium',
    description: 'Statin medication used to lower cholesterol and reduce risk of heart disease and stroke.',
    category: 'Heart Health',
    subcategory: 'Cholesterol',
    image: 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=400&h=400&fit=crop',
    prescriptionRequired: true,
    dosage: '20mg',
    strength: '20mg',
    form: 'Tablet',
    manufacturer: 'Lipitor',
    activeIngredients: ['Atorvastatin Calcium 20mg'],
    uses: ['High cholesterol', 'Heart disease prevention', 'Stroke prevention'],
    sideEffects: ['Muscle pain', 'Joint pain', 'Nausea', 'Headache'],
    warnings: ['Avoid grapefruit juice', 'Monitor liver function', 'Report muscle pain immediately'],
    storageInstructions: 'Store at room temperature, protect from light',
    isGenericAvailable: true,
    genericSavings: 45,
    requiresRefrigeration: false,
    isControlledSubstance: false,
    vendorPricing: generateVendorPricing(29.99, ['vendor-1', 'vendor-2', 'vendor-3', 'vendor-5']),
    averageRating: 4.8,
    totalReviews: 672,
    isFeatured: true,
    isLatest: false,
    isDiscounted: false,
    lowestPrice: 27.49,
    highestPrice: 32.99,
    vendorCount: 4,
    createdAt: new Date('2024-08-10'),
    updatedAt: new Date('2025-01-12'),
  },
  {
    id: '5',
    name: 'Amoxicillin 500mg',
    genericName: 'Amoxicillin',
    description: 'Penicillin antibiotic used to treat bacterial infections including ear infections, pneumonia, and urinary tract infections.',
    category: 'Antibiotics',
    subcategory: 'Penicillins',
    image: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400&h=400&fit=crop',
    prescriptionRequired: true,
    dosage: '500mg',
    strength: '500mg',
    form: 'Capsule',
    manufacturer: 'GlaxoSmithKline',
    activeIngredients: ['Amoxicillin 500mg'],
    uses: ['Bacterial infections', 'Ear infections', 'Pneumonia', 'UTIs'],
    sideEffects: ['Diarrhea', 'Nausea', 'Skin rash', 'Vomiting'],
    warnings: ['Complete full course', 'Do not use if allergic to penicillin', 'May reduce birth control effectiveness'],
    storageInstructions: 'Store at room temperature, keep away from moisture',
    isGenericAvailable: true,
    requiresRefrigeration: false,
    isControlledSubstance: false,
    vendorPricing: generateVendorPricing(15.99, ['vendor-1', 'vendor-2', 'vendor-4', 'vendor-6']),
    averageRating: 4.4,
    totalReviews: 321,
    isFeatured: false,
    isLatest: true,
    isDiscounted: false,
    lowestPrice: 14.49,
    highestPrice: 17.99,
    vendorCount: 4,
    createdAt: new Date('2025-01-05'),
    updatedAt: new Date('2025-01-20'),
  },
  {
    id: '6',
    name: 'Omeprazole 20mg',
    genericName: 'Omeprazole',
    description: 'Proton pump inhibitor that reduces stomach acid production. Used to treat heartburn, GERD, and stomach ulcers.',
    category: 'Digestive Health',
    subcategory: 'Acid Reducers',
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400&h=400&fit=crop',
    prescriptionRequired: false,
    dosage: '20mg',
    strength: '20mg',
    form: 'Capsule',
    manufacturer: 'Prilosec',
    activeIngredients: ['Omeprazole 20mg'],
    uses: ['Heartburn', 'GERD', 'Stomach ulcers', 'Acid reflux'],
    sideEffects: ['Headache', 'Stomach pain', 'Nausea', 'Diarrhea'],
    warnings: ['Take before meals', 'Not for immediate heartburn relief', 'May take 1-4 days to work'],
    storageInstructions: 'Store at room temperature, protect from moisture',
    isGenericAvailable: true,
    genericSavings: 30,
    requiresRefrigeration: false,
    isControlledSubstance: false,
    vendorPricing: generateVendorPricing(18.99, ['vendor-1', 'vendor-3', 'vendor-5', 'vendor-6'], true),
    averageRating: 4.6,
    totalReviews: 445,
    isFeatured: true,
    isLatest: false,
    isDiscounted: true,
    lowestPrice: 15.99,
    highestPrice: 20.99,
    vendorCount: 4,
    createdAt: new Date('2024-11-15'),
    updatedAt: new Date('2025-01-10'),
  },
  {
    id: '7',
    name: 'Levothyroxine 50mcg',
    genericName: 'Levothyroxine Sodium',
    description: 'Thyroid hormone replacement used to treat hypothyroidism (underactive thyroid gland).',
    category: 'Thyroid',
    subcategory: 'Hormone Replacement',
    image: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?w=400&h=400&fit=crop',
    prescriptionRequired: true,
    dosage: '50mcg',
    strength: '50mcg',
    form: 'Tablet',
    manufacturer: 'Synthroid',
    activeIngredients: ['Levothyroxine Sodium 50mcg'],
    uses: ['Hypothyroidism', 'Thyroid hormone deficiency', 'Goiter treatment'],
    sideEffects: ['Weight changes', 'Headache', 'Insomnia', 'Nervousness'],
    warnings: ['Take on empty stomach', 'Take consistently at same time', 'Separate from calcium/iron supplements'],
    storageInstructions: 'Store at room temperature, protect from light and moisture',
    isGenericAvailable: true,
    genericSavings: 40,
    requiresRefrigeration: false,
    isControlledSubstance: false,
    vendorPricing: generateVendorPricing(22.99, ['vendor-1', 'vendor-2', 'vendor-5', 'vendor-6']),
    averageRating: 4.7,
    totalReviews: 512,
    isFeatured: false,
    isLatest: true,
    isDiscounted: false,
    lowestPrice: 20.99,
    highestPrice: 24.99,
    vendorCount: 4,
    createdAt: new Date('2025-01-08'),
    updatedAt: new Date('2025-01-22'),
  },
  {
    id: '8',
    name: 'Ibuprofen 400mg',
    genericName: 'Ibuprofen',
    description: 'Nonsteroidal anti-inflammatory drug (NSAID) used to reduce fever and treat pain or inflammation.',
    category: 'Pain Relief',
    subcategory: 'NSAIDs',
    image: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&h=400&fit=crop',
    prescriptionRequired: false,
    dosage: '400mg',
    strength: '400mg',
    form: 'Tablet',
    manufacturer: 'Advil',
    activeIngredients: ['Ibuprofen 400mg'],
    uses: ['Pain relief', 'Fever reduction', 'Inflammation', 'Headaches', 'Arthritis'],
    sideEffects: ['Upset stomach', 'Heartburn', 'Dizziness', 'Rash'],
    warnings: ['Take with food', 'Do not use if you have stomach ulcers', 'May increase heart attack risk with long-term use'],
    storageInstructions: 'Store at room temperature, keep dry',
    isGenericAvailable: true,
    genericSavings: 25,
    requiresRefrigeration: false,
    isControlledSubstance: false,
    vendorPricing: generateVendorPricing(13.99, ['vendor-1', 'vendor-2', 'vendor-3', 'vendor-4', 'vendor-5'], true),
    averageRating: 4.5,
    totalReviews: 678,
    isFeatured: true,
    isLatest: false,
    isDiscounted: true,
    lowestPrice: 11.99,
    highestPrice: 15.49,
    vendorCount: 5,
    createdAt: new Date('2024-07-20'),
    updatedAt: new Date('2025-01-19'),
  },
  {
    id: '9',
    name: 'Amlodipine 5mg',
    genericName: 'Amlodipine Besylate',
    description: 'Calcium channel blocker used to treat high blood pressure and chest pain (angina).',
    category: 'Heart Health',
    subcategory: 'Blood Pressure',
    image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400&h=400&fit=crop',
    prescriptionRequired: true,
    dosage: '5mg',
    strength: '5mg',
    form: 'Tablet',
    manufacturer: 'Norvasc',
    activeIngredients: ['Amlodipine Besylate 5mg'],
    uses: ['High blood pressure', 'Chest pain', 'Coronary artery disease'],
    sideEffects: ['Swelling of ankles', 'Dizziness', 'Flushing', 'Palpitations'],
    warnings: ['May cause dizziness', 'Avoid grapefruit', 'Rise slowly from sitting/lying position'],
    storageInstructions: 'Store at room temperature, protect from light',
    isGenericAvailable: true,
    genericSavings: 50,
    requiresRefrigeration: false,
    isControlledSubstance: false,
    vendorPricing: generateVendorPricing(21.99, ['vendor-1', 'vendor-3', 'vendor-4', 'vendor-6']),
    averageRating: 4.6,
    totalReviews: 389,
    isFeatured: false,
    isLatest: true,
    isDiscounted: false,
    lowestPrice: 19.99,
    highestPrice: 23.99,
    vendorCount: 4,
    createdAt: new Date('2025-01-12'),
    updatedAt: new Date('2025-01-23'),
  },
  {
    id: '10',
    name: 'Cetirizine 10mg',
    genericName: 'Cetirizine HCl',
    description: 'Antihistamine used to relieve allergy symptoms such as watery eyes, runny nose, sneezing, and itching.',
    category: 'Allergy',
    subcategory: 'Antihistamines',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop',
    prescriptionRequired: false,
    dosage: '10mg',
    strength: '10mg',
    form: 'Tablet',
    manufacturer: 'Zyrtec',
    activeIngredients: ['Cetirizine Hydrochloride 10mg'],
    uses: ['Seasonal allergies', 'Hay fever', 'Hives', 'Itching', 'Watery eyes'],
    sideEffects: ['Drowsiness', 'Dry mouth', 'Fatigue', 'Headache'],
    warnings: ['May cause drowsiness', 'Avoid alcohol', 'Use caution when driving'],
    storageInstructions: 'Store at room temperature, keep dry',
    isGenericAvailable: true,
    genericSavings: 35,
    requiresRefrigeration: false,
    isControlledSubstance: false,
    vendorPricing: generateVendorPricing(16.99, ['vendor-2', 'vendor-3', 'vendor-5', 'vendor-6'], true),
    averageRating: 4.7,
    totalReviews: 523,
    isFeatured: true,
    isLatest: false,
    isDiscounted: true,
    lowestPrice: 13.99,
    highestPrice: 18.49,
    vendorCount: 4,
    createdAt: new Date('2024-10-28'),
    updatedAt: new Date('2025-01-14'),
  },
];

export const getFeaturedProducts = () => mockProductsEnhanced.filter((p) => p.isFeatured);
export const getLatestProducts = () => mockProductsEnhanced.filter((p) => p.isLatest);
export const getDiscountedProducts = () => mockProductsEnhanced.filter((p) => p.isDiscounted);
export const getProductById = (id: string) => mockProductsEnhanced.find((p) => p.id === id);
